[package]
name = "cazanw-packer"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["cazanw", "cazanw-bin", "post-build"]

[[bin]]
name = "cazanw"
path = "cazanw-bin/src/main.rs"


[profile.release]
opt-level = "s"
