[package]
name = "cazanw-bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cazanw"
path = "src/main.rs"

[dependencies]
argh = "0.1.12"
cazan-common = "0.1.1"
serde_json = "1.0.116"
image = "0.25.1"
cprint = {  version = "0.5.0", features = ["ceprint"] }

